# Generated by Django 5.0.4 on 2025-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_venta_descuento_ventaitem_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='stock_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='stock_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
