# Generated by Django 5.0.4 on 2025-08-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_pedido_moneda'),
        ('ventas', '0005_venta_completado_venta_stock_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('aplicado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.cliente')),
                ('iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.iva')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.moneda')),
                ('venta_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stock_aplicado', models.BooleanField(default=False)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.notacredito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
    ]
