# Generated by Django 5.0.4 on 2025-08-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_pedido_moneda'),
        ('ventas', '0006_venta_anulada_notacredito_notacreditoitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ventaitem',
            constraint=models.UniqueConstraint(fields=('venta', 'producto'), name='unique_venta_producto'),
        ),
    ]
