# Generated by Django 5.0.4 on 2025-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_optimo',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
