# Generated by Django 5.0.4 on 2025-05-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_stock_optimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_optimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
