# Generated by Django 5.0.4 on 2025-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_formapago_pedido_fechaestimadaentrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
