# Generated by Django 5.0.4 on 2025-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedido_stock_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='stock_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
