# Generated by Django 5.0.4 on 2025-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pedidoitem_stock_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
