# Generated by Django 5.0.4 on 2025-08-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_vendedor'),
        ('ventas', '0005_venta_completado_venta_stock_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.moneda'),
        ),
    ]
