# Generated by Django 5.0.4 on 2025-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_pedido_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
