# Generated by Django 5.0.4 on 2025-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_stock_optimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=200, unique=True)),
                ('nombreProv', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ManyToManyField(related_name='proveedores', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombreEmpresa'],
            },
        ),
    ]
