# Generated by Django 5.0.4 on 2025-07-19 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('estacion', models.CharField(max_length=50)),
                ('mesDesde', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes Hasta')),
                ('diaHasta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes Hasta')),
                ('diaDesde', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Mes Hasta')),
                ('mesHasta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Mes Hasta')),
                ('stockMin', models.PositiveIntegerField(blank=True, null=True)),
                ('stockMax', models.PositiveIntegerField(blank=True, null=True)),
                ('producto', models.ManyToManyField(related_name='estacionalidades', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Estacionalidad',
                'verbose_name_plural': 'Estacionalidades',
                'ordering': ['nombre'],
            },
        ),
    ]
