# Generated by Django 5.0.4 on 2025-07-21 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_estacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionalidad',
            name='diaDesde',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia Hasta'),
        ),
        migrations.AlterField(
            model_name='estacionalidad',
            name='diaHasta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia Hasta'),
        ),
        migrations.AlterField(
            model_name='estacionalidad',
            name='mesHasta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes Hasta'),
        ),
    ]
