# Generated by Django 5.0.4 on 2025-07-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_estacionalidad_diadesde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.proveedor'),
        ),
    ]
