name: Django CI (sin tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar migraciones y aplicar migrate
        env:
          CI: "true"
        run: |
          python manage.py makemigrations --check --dry-run
          python manage.py migrate --noinput
          
      - name: Verificar migraciones y aplicar migrate
        env:
          CI: "true"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py makemigrations --check --dry-run
          python manage.py migrate --noinput

